### ISSUE TITLE
Wrong probabilities, probably flipped in kcapp api (example)

### ISSUE THREAD

**Issue by Chmieloo** [kcapp/odds-game#112]
{
    "id": 11679,
    "created_at": "2022-06-10T17:30:00Z",
    "updated_at": "2022-06-10T17:26:45Z",
    "is_finished": true,
    "is_abandoned": false,
    "is_started": false,
    "is_walkover": false,
    "is_players_decided": true,
    "winner_id": 1,
    "players": [
      11,
      1
    ],
    "player_elo": {
      "1": 1644,
      "11": 1805
    },
    "player_winning_probabilities": {
      "1": 0.284,
      "11": 0.716
    },
    "player_odds": {
      "1": 3.526,
      "11": 1.396
    }
  },

**Comment by thordy** [comment]
Was an issue with ordering in kcapp-api, fixed in latest develop
